name: 'DeployForge Build Image'
description: 'Build customized Windows deployment images using DeployForge'
author: 'DeployForge Team'

branding:
  icon: 'package'
  color: 'blue'

inputs:
  image-path:
    description: 'Path to the source Windows image (WIM, ESD, or ISO)'
    required: true

  profile:
    description: 'Profile to apply (gamer, developer, enterprise, student, creator, custom)'
    required: false
    default: 'gamer'

  output-path:
    description: 'Path for the output customized image'
    required: false
    default: 'custom.wim'

  preset:
    description: 'Optional preset name to apply instead of profile'
    required: false

  python-version:
    description: 'Python version to use'
    required: false
    default: '3.11'

  validate:
    description: 'Validate image after build (true/false)'
    required: false
    default: 'true'

  generate-report:
    description: 'Generate analysis report (true/false)'
    required: false
    default: 'false'

  report-format:
    description: 'Report format (text, json, html)'
    required: false
    default: 'html'

outputs:
  output-image:
    description: 'Path to the generated image'
    value: ${{ steps.build.outputs.output-image }}

  validation-result:
    description: 'Validation result (passed/failed)'
    value: ${{ steps.validate.outputs.result }}

  report-path:
    description: 'Path to the analysis report'
    value: ${{ steps.report.outputs.report-path }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install DeployForge
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install deployforge

    - name: Build Image
      id: build
      shell: bash
      run: |
        echo "Building image with DeployForge..."

        if [ -n "${{ inputs.preset }}" ]; then
          echo "Using preset: ${{ inputs.preset }}"
          python -m deployforge.cli preset apply \
            "${{ inputs.preset }}" \
            "${{ inputs.image-path }}" \
            --output "${{ inputs.output-path }}"
        else
          echo "Using profile: ${{ inputs.profile }}"
          python -m deployforge.cli build \
            "${{ inputs.image-path }}" \
            --profile "${{ inputs.profile }}" \
            --output "${{ inputs.output-path }}"
        fi

        echo "output-image=${{ inputs.output-path }}" >> $GITHUB_OUTPUT
        echo "✅ Build completed!"

    - name: Validate Image
      id: validate
      if: inputs.validate == 'true'
      shell: bash
      run: |
        echo "Validating image..."
        if python -m deployforge.cli validate "${{ inputs.output-path }}"; then
          echo "result=passed" >> $GITHUB_OUTPUT
          echo "✅ Validation passed!"
        else
          echo "result=failed" >> $GITHUB_OUTPUT
          echo "❌ Validation failed!"
          exit 1
        fi

    - name: Generate Report
      id: report
      if: inputs.generate-report == 'true'
      shell: bash
      run: |
        REPORT_PATH="deployforge-report.${{ inputs.report-format }}"
        echo "Generating ${{ inputs.report-format }} report..."

        python -m deployforge.cli analyze \
          "${{ inputs.output-path }}" \
          --format "${{ inputs.report-format }}" \
          --output "$REPORT_PATH"

        echo "report-path=$REPORT_PATH" >> $GITHUB_OUTPUT
        echo "✅ Report generated: $REPORT_PATH"

    - name: Upload Report
      if: inputs.generate-report == 'true'
      uses: actions/upload-artifact@v3
      with:
        name: deployforge-report
        path: ${{ steps.report.outputs.report-path }}
