using System.Collections.ObjectModel;
using System.Text.RegularExpressions;
using CommunityToolkit.Mvvm.Input;
using DeployForge.Desktop.Services;
using Microsoft.Extensions.Logging;

namespace DeployForge.Desktop.ViewModels;

/// <summary>
/// Settings ViewModel
/// </summary>
public partial class SettingsViewModel : ViewModelBase
{
    private readonly IApiClient _apiClient;
    private readonly IDialogService _dialogService;
    private readonly ILogger<SettingsViewModel> _logger;

    // API Settings
    private string _apiBaseUrl = "http://localhost:5000";
    private int _apiTimeout = 30;
    private bool _useHttps = false;

    // Application Settings
    private string _theme = "Light";
    private string _language = "English";
    private bool _checkForUpdates = true;
    private bool _minimizeToTray = false;
    private bool _startWithWindows = false;

    // Notification Settings (Basic)
    private bool _showNotifications = true;
    private bool _playSound = true;
    private bool _showDesktopNotifications = true;

    // Performance Settings
    private int _maxConcurrentOperations = 2;
    private bool _enableHardwareAcceleration = true;
    private int _cacheSize = 500;

    // Logging Settings
    private string _logLevel = "Information";
    private bool _enableFileLogging = true;
    private bool _enableDebugLogging = false;
    private string _logDirectory = @"C:\DeployForge\Logs";

    // Monitoring & Alert Settings
    private double _cpuThreshold = 80.0;
    private double _memoryThreshold = 85.0;
    private double _diskThreshold = 90.0;
    private int _metricsRetentionDays = 30;
    private int _alertRetentionDays = 90;
    private bool _enableAlertsMonitoring = true;

    // Email Notification Settings
    private bool _enableEmailNotifications = false;
    private string _smtpServer = string.Empty;
    private int _smtpPort = 587;
    private bool _smtpUseSsl = true;
    private string _smtpUsername = string.Empty;
    private string _smtpPassword = string.Empty;
    private string _emailFrom = string.Empty;
    private string _emailTo = string.Empty;

    // Slack Notification Settings
    private bool _enableSlackNotifications = false;
    private string _slackWebhookUrl = string.Empty;
    private string _slackChannel = "#deployforge";
    private string _slackUsername = "DeployForge";

    // Teams Notification Settings
    private bool _enableTeamsNotifications = false;
    private string _teamsWebhookUrl = string.Empty;

    // Webhook Notification Settings
    private bool _enableWebhookNotifications = false;
    private string _webhookUrl = string.Empty;
    private string _webhookMethod = "POST";
    private string _webhookAuthHeader = string.Empty;

    // Report Settings
    private string _reportOutputDirectory = @"C:\DeployForge\Reports";
    private string _defaultReportFormat = "PDF";
    private bool _includeChartsInReports = true;
    private bool _includeSummarySection = true;
    private bool _includeDetailedLogs = false;
    private int _reportRetentionDays = 60;
    private bool _autoGenerateDailyReport = false;
    private string _dailyReportTime = "09:00";

    // Schedule Settings
    private int _maxConcurrentScheduledJobs = 5;
    private int _scheduleRetentionDays = 180;
    private bool _enableScheduledJobs = true;
    private string _defaultTimeZone = "UTC";
    private bool _sendScheduleNotifications = true;

    #region API Settings Properties

    public string ApiBaseUrl
    {
        get => _apiBaseUrl;
        set => SetProperty(ref _apiBaseUrl, value);
    }

    public int ApiTimeout
    {
        get => _apiTimeout;
        set => SetProperty(ref _apiTimeout, value);
    }

    public bool UseHttps
    {
        get => _useHttps;
        set => SetProperty(ref _useHttps, value);
    }

    #endregion

    #region Application Settings Properties

    public string Theme
    {
        get => _theme;
        set
        {
            if (SetProperty(ref _theme, value))
            {
                ApplyTheme(value);
            }
        }
    }

    public string Language
    {
        get => _language;
        set => SetProperty(ref _language, value);
    }

    public bool CheckForUpdates
    {
        get => _checkForUpdates;
        set => SetProperty(ref _checkForUpdates, value);
    }

    public bool MinimizeToTray
    {
        get => _minimizeToTray;
        set => SetProperty(ref _minimizeToTray, value);
    }

    public bool StartWithWindows
    {
        get => _startWithWindows;
        set => SetProperty(ref _startWithWindows, value);
    }

    #endregion

    #region Notification Settings Properties

    public bool ShowNotifications
    {
        get => _showNotifications;
        set => SetProperty(ref _showNotifications, value);
    }

    public bool PlaySound
    {
        get => _playSound;
        set => SetProperty(ref _playSound, value);
    }

    public bool ShowDesktopNotifications
    {
        get => _showDesktopNotifications;
        set => SetProperty(ref _showDesktopNotifications, value);
    }

    #endregion

    #region Performance Settings Properties

    public int MaxConcurrentOperations
    {
        get => _maxConcurrentOperations;
        set => SetProperty(ref _maxConcurrentOperations, value);
    }

    public bool EnableHardwareAcceleration
    {
        get => _enableHardwareAcceleration;
        set => SetProperty(ref _enableHardwareAcceleration, value);
    }

    public int CacheSize
    {
        get => _cacheSize;
        set => SetProperty(ref _cacheSize, value);
    }

    #endregion

    #region Logging Settings Properties

    public string LogLevel
    {
        get => _logLevel;
        set => SetProperty(ref _logLevel, value);
    }

    public bool EnableFileLogging
    {
        get => _enableFileLogging;
        set => SetProperty(ref _enableFileLogging, value);
    }

    public bool EnableDebugLogging
    {
        get => _enableDebugLogging;
        set => SetProperty(ref _enableDebugLogging, value);
    }

    public string LogDirectory
    {
        get => _logDirectory;
        set => SetProperty(ref _logDirectory, value);
    }

    #endregion

    #region Monitoring & Alert Settings Properties

    public double CpuThreshold
    {
        get => _cpuThreshold;
        set => SetProperty(ref _cpuThreshold, value);
    }

    public double MemoryThreshold
    {
        get => _memoryThreshold;
        set => SetProperty(ref _memoryThreshold, value);
    }

    public double DiskThreshold
    {
        get => _diskThreshold;
        set => SetProperty(ref _diskThreshold, value);
    }

    public int MetricsRetentionDays
    {
        get => _metricsRetentionDays;
        set => SetProperty(ref _metricsRetentionDays, value);
    }

    public int AlertRetentionDays
    {
        get => _alertRetentionDays;
        set => SetProperty(ref _alertRetentionDays, value);
    }

    public bool EnableAlertsMonitoring
    {
        get => _enableAlertsMonitoring;
        set => SetProperty(ref _enableAlertsMonitoring, value);
    }

    #endregion

    #region Email Notification Settings Properties

    public bool EnableEmailNotifications
    {
        get => _enableEmailNotifications;
        set => SetProperty(ref _enableEmailNotifications, value);
    }

    public string SmtpServer
    {
        get => _smtpServer;
        set => SetProperty(ref _smtpServer, value);
    }

    public int SmtpPort
    {
        get => _smtpPort;
        set => SetProperty(ref _smtpPort, value);
    }

    public bool SmtpUseSsl
    {
        get => _smtpUseSsl;
        set => SetProperty(ref _smtpUseSsl, value);
    }

    public string SmtpUsername
    {
        get => _smtpUsername;
        set => SetProperty(ref _smtpUsername, value);
    }

    public string SmtpPassword
    {
        get => _smtpPassword;
        set => SetProperty(ref _smtpPassword, value);
    }

    public string EmailFrom
    {
        get => _emailFrom;
        set => SetProperty(ref _emailFrom, value);
    }

    public string EmailTo
    {
        get => _emailTo;
        set => SetProperty(ref _emailTo, value);
    }

    #endregion

    #region Slack Notification Settings Properties

    public bool EnableSlackNotifications
    {
        get => _enableSlackNotifications;
        set => SetProperty(ref _enableSlackNotifications, value);
    }

    public string SlackWebhookUrl
    {
        get => _slackWebhookUrl;
        set => SetProperty(ref _slackWebhookUrl, value);
    }

    public string SlackChannel
    {
        get => _slackChannel;
        set => SetProperty(ref _slackChannel, value);
    }

    public string SlackUsername
    {
        get => _slackUsername;
        set => SetProperty(ref _slackUsername, value);
    }

    #endregion

    #region Teams Notification Settings Properties

    public bool EnableTeamsNotifications
    {
        get => _enableTeamsNotifications;
        set => SetProperty(ref _enableTeamsNotifications, value);
    }

    public string TeamsWebhookUrl
    {
        get => _teamsWebhookUrl;
        set => SetProperty(ref _teamsWebhookUrl, value);
    }

    #endregion

    #region Webhook Notification Settings Properties

    public bool EnableWebhookNotifications
    {
        get => _enableWebhookNotifications;
        set => SetProperty(ref _enableWebhookNotifications, value);
    }

    public string WebhookUrl
    {
        get => _webhookUrl;
        set => SetProperty(ref _webhookUrl, value);
    }

    public string WebhookMethod
    {
        get => _webhookMethod;
        set => SetProperty(ref _webhookMethod, value);
    }

    public string WebhookAuthHeader
    {
        get => _webhookAuthHeader;
        set => SetProperty(ref _webhookAuthHeader, value);
    }

    #endregion

    #region Report Settings Properties

    public string ReportOutputDirectory
    {
        get => _reportOutputDirectory;
        set => SetProperty(ref _reportOutputDirectory, value);
    }

    public string DefaultReportFormat
    {
        get => _defaultReportFormat;
        set => SetProperty(ref _defaultReportFormat, value);
    }

    public bool IncludeChartsInReports
    {
        get => _includeChartsInReports;
        set => SetProperty(ref _includeChartsInReports, value);
    }

    public bool IncludeSummarySection
    {
        get => _includeSummarySection;
        set => SetProperty(ref _includeSummarySection, value);
    }

    public bool IncludeDetailedLogs
    {
        get => _includeDetailedLogs;
        set => SetProperty(ref _includeDetailedLogs, value);
    }

    public int ReportRetentionDays
    {
        get => _reportRetentionDays;
        set => SetProperty(ref _reportRetentionDays, value);
    }

    public bool AutoGenerateDailyReport
    {
        get => _autoGenerateDailyReport;
        set => SetProperty(ref _autoGenerateDailyReport, value);
    }

    public string DailyReportTime
    {
        get => _dailyReportTime;
        set => SetProperty(ref _dailyReportTime, value);
    }

    #endregion

    #region Schedule Settings Properties

    public int MaxConcurrentScheduledJobs
    {
        get => _maxConcurrentScheduledJobs;
        set => SetProperty(ref _maxConcurrentScheduledJobs, value);
    }

    public int ScheduleRetentionDays
    {
        get => _scheduleRetentionDays;
        set => SetProperty(ref _scheduleRetentionDays, value);
    }

    public bool EnableScheduledJobs
    {
        get => _enableScheduledJobs;
        set => SetProperty(ref _enableScheduledJobs, value);
    }

    public string DefaultTimeZone
    {
        get => _defaultTimeZone;
        set => SetProperty(ref _defaultTimeZone, value);
    }

    public bool SendScheduleNotifications
    {
        get => _sendScheduleNotifications;
        set => SetProperty(ref _sendScheduleNotifications, value);
    }

    #endregion

    public ObservableCollection<string> Themes { get; } = new() { "Light", "Dark", "System" };
    public ObservableCollection<string> Languages { get; } = new() { "English", "Spanish", "French", "German" };
    public ObservableCollection<string> LogLevels { get; } = new()
    {
        "Verbose", "Debug", "Information", "Warning", "Error", "Critical"
    };
    public ObservableCollection<string> ReportFormats { get; } = new() { "PDF", "HTML", "JSON" };
    public ObservableCollection<string> WebhookMethods { get; } = new() { "GET", "POST", "PUT" };
    public ObservableCollection<string> TimeZones { get; } = new()
    {
        "UTC", "Eastern Standard Time", "Central Standard Time",
        "Mountain Standard Time", "Pacific Standard Time"
    };

    public SettingsViewModel(
        IApiClient apiClient,
        IDialogService dialogService,
        ILogger<SettingsViewModel> logger)
    {
        _apiClient = apiClient;
        _dialogService = dialogService;
        _logger = logger;
    }

    public override async Task InitializeAsync()
    {
        await base.InitializeAsync();
        LoadSettings();
    }

    [RelayCommand]
    private async Task SaveSettingsAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Saving settings...";

            // In a real implementation, save to configuration file or API
            await Task.Delay(500); // Simulate save operation

            StatusMessage = "Settings saved successfully";
            _dialogService.ShowSuccessMessage("Success", "Settings saved successfully");
            _logger.LogInformation("Settings saved successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to save settings");
            StatusMessage = "Failed to save settings";
            _dialogService.ShowErrorMessage("Save Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private void ResetSettings()
    {
        var confirm = _dialogService.ShowConfirmation(
            "Reset Settings",
            "Are you sure you want to reset all settings to defaults?");

        if (!confirm) return;

        // Reset to defaults - General Settings
        ApiBaseUrl = "http://localhost:5000";
        ApiTimeout = 30;
        UseHttps = false;

        Theme = "Light";
        Language = "English";
        CheckForUpdates = true;
        MinimizeToTray = false;
        StartWithWindows = false;

        ShowNotifications = true;
        PlaySound = true;
        ShowDesktopNotifications = true;

        MaxConcurrentOperations = 2;
        EnableHardwareAcceleration = true;
        CacheSize = 500;

        LogLevel = "Information";
        EnableFileLogging = true;
        EnableDebugLogging = false;
        LogDirectory = @"C:\DeployForge\Logs";

        // Reset Monitoring & Alert Settings
        CpuThreshold = 80.0;
        MemoryThreshold = 85.0;
        DiskThreshold = 90.0;
        MetricsRetentionDays = 30;
        AlertRetentionDays = 90;
        EnableAlertsMonitoring = true;

        // Reset Email Settings
        EnableEmailNotifications = false;
        SmtpServer = string.Empty;
        SmtpPort = 587;
        SmtpUseSsl = true;
        SmtpUsername = string.Empty;
        SmtpPassword = string.Empty;
        EmailFrom = string.Empty;
        EmailTo = string.Empty;

        // Reset Slack Settings
        EnableSlackNotifications = false;
        SlackWebhookUrl = string.Empty;
        SlackChannel = "#deployforge";
        SlackUsername = "DeployForge";

        // Reset Teams Settings
        EnableTeamsNotifications = false;
        TeamsWebhookUrl = string.Empty;

        // Reset Webhook Settings
        EnableWebhookNotifications = false;
        WebhookUrl = string.Empty;
        WebhookMethod = "POST";
        WebhookAuthHeader = string.Empty;

        // Reset Report Settings
        ReportOutputDirectory = @"C:\DeployForge\Reports";
        DefaultReportFormat = "PDF";
        IncludeChartsInReports = true;
        IncludeSummarySection = true;
        IncludeDetailedLogs = false;
        ReportRetentionDays = 60;
        AutoGenerateDailyReport = false;
        DailyReportTime = "09:00";

        // Reset Schedule Settings
        MaxConcurrentScheduledJobs = 5;
        ScheduleRetentionDays = 180;
        EnableScheduledJobs = true;
        DefaultTimeZone = "UTC";
        SendScheduleNotifications = true;

        _dialogService.ShowInformationMessage("Reset Complete", "All settings have been reset to defaults");
        _logger.LogInformation("Settings reset to defaults");
    }

    [RelayCommand]
    private async Task TestConnectionAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Testing API connection...";

            var health = await _apiClient.GetAsync<object>("health");

            if (health != null)
            {
                StatusMessage = "API connection successful";
                _dialogService.ShowSuccessMessage("Success", $"Connected to API at {ApiBaseUrl}");
            }
            else
            {
                StatusMessage = "API connection failed";
                _dialogService.ShowWarningMessage("Connection Failed", "Unable to connect to the API");
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to test API connection");
            StatusMessage = "API connection failed";
            _dialogService.ShowErrorMessage("Connection Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private void BrowseLogDirectory()
    {
        var path = _dialogService.ShowFolderBrowserDialog("Select Log Directory");
        if (!string.IsNullOrEmpty(path))
        {
            LogDirectory = path;
        }
    }

    [RelayCommand]
    private void ClearCache()
    {
        var confirm = _dialogService.ShowConfirmation(
            "Clear Cache",
            "Are you sure you want to clear the application cache?");

        if (!confirm) return;

        try
        {
            // In a real implementation, clear actual cache
            _dialogService.ShowSuccessMessage("Success", "Cache cleared successfully");
            _logger.LogInformation("Cache cleared");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to clear cache");
            _dialogService.ShowErrorMessage("Clear Failed", ex.Message);
        }
    }

    [RelayCommand]
    private void OpenLogDirectory()
    {
        try
        {
            if (Directory.Exists(LogDirectory))
            {
                System.Diagnostics.Process.Start("explorer.exe", LogDirectory);
            }
            else
            {
                _dialogService.ShowWarningMessage("Directory Not Found", "Log directory does not exist");
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to open log directory");
            _dialogService.ShowErrorMessage("Open Failed", ex.Message);
        }
    }

    [RelayCommand]
    private async Task CheckForUpdatesAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Checking for updates...";

            await Task.Delay(1000); // Simulate update check

            StatusMessage = "No updates available";
            _dialogService.ShowInformationMessage("Up to Date", "You are running the latest version of DeployForge");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to check for updates");
            StatusMessage = "Update check failed";
            _dialogService.ShowErrorMessage("Update Check Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task TestEmailNotificationAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Testing email notification...";

            var settings = new
            {
                SmtpServer = SmtpServer,
                SmtpPort = SmtpPort,
                UseSsl = SmtpUseSsl,
                Username = SmtpUsername,
                Password = SmtpPassword,
                From = EmailFrom,
                To = EmailTo
            };

            await _apiClient.PostAsync<object, object>("notifications/test/email", settings);

            StatusMessage = "Test email sent successfully";
            _dialogService.ShowSuccessMessage("Success", "Test email sent successfully. Check your inbox.");
            _logger.LogInformation("Test email sent successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send test email");
            StatusMessage = "Failed to send test email";
            _dialogService.ShowErrorMessage("Test Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task TestSlackNotificationAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Testing Slack notification...";

            var settings = new
            {
                WebhookUrl = SlackWebhookUrl,
                Channel = SlackChannel,
                Username = SlackUsername
            };

            await _apiClient.PostAsync<object, object>("notifications/test/slack", settings);

            StatusMessage = "Test Slack message sent successfully";
            _dialogService.ShowSuccessMessage("Success", "Test message sent to Slack successfully.");
            _logger.LogInformation("Test Slack message sent successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send test Slack message");
            StatusMessage = "Failed to send test Slack message";
            _dialogService.ShowErrorMessage("Test Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task TestTeamsNotificationAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Testing Teams notification...";

            var settings = new { WebhookUrl = TeamsWebhookUrl };

            await _apiClient.PostAsync<object, object>("notifications/test/teams", settings);

            StatusMessage = "Test Teams message sent successfully";
            _dialogService.ShowSuccessMessage("Success", "Test message sent to Teams successfully.");
            _logger.LogInformation("Test Teams message sent successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send test Teams message");
            StatusMessage = "Failed to send test Teams message";
            _dialogService.ShowErrorMessage("Test Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task TestWebhookNotificationAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Testing webhook notification...";

            var settings = new
            {
                Url = WebhookUrl,
                Method = WebhookMethod,
                AuthHeader = WebhookAuthHeader
            };

            await _apiClient.PostAsync<object, object>("notifications/test/webhook", settings);

            StatusMessage = "Test webhook sent successfully";
            _dialogService.ShowSuccessMessage("Success", "Test webhook sent successfully.");
            _logger.LogInformation("Test webhook sent successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to send test webhook");
            StatusMessage = "Failed to send test webhook";
            _dialogService.ShowErrorMessage("Test Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private void BrowseReportDirectory()
    {
        var path = _dialogService.ShowFolderBrowserDialog("Select Report Output Directory");
        if (!string.IsNullOrEmpty(path))
        {
            ReportOutputDirectory = path;
        }
    }

    [RelayCommand]
    private void OpenReportDirectory()
    {
        try
        {
            if (Directory.Exists(ReportOutputDirectory))
            {
                System.Diagnostics.Process.Start("explorer.exe", ReportOutputDirectory);
            }
            else
            {
                _dialogService.ShowWarningMessage("Directory Not Found", "Report directory does not exist");
            }
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to open report directory");
            _dialogService.ShowErrorMessage("Open Failed", ex.Message);
        }
    }

    [RelayCommand]
    private async Task ConfigureAlertThresholdsAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Configuring alert thresholds...";

            var thresholds = new
            {
                CpuThreshold = CpuThreshold,
                MemoryThreshold = MemoryThreshold,
                DiskThreshold = DiskThreshold,
                Enabled = EnableAlertsMonitoring
            };

            await _apiClient.PostAsync<object, object>("health/alerts/configure", thresholds);

            StatusMessage = "Alert thresholds configured successfully";
            _dialogService.ShowSuccessMessage("Success", "Alert thresholds have been configured successfully.");
            _logger.LogInformation("Alert thresholds configured: CPU={CpuThreshold}%, Memory={MemoryThreshold}%, Disk={DiskThreshold}%",
                CpuThreshold, MemoryThreshold, DiskThreshold);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to configure alert thresholds");
            StatusMessage = "Failed to configure alert thresholds";
            _dialogService.ShowErrorMessage("Configuration Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    [RelayCommand]
    private async Task SaveNotificationSettingsAsync()
    {
        try
        {
            IsBusy = true;
            StatusMessage = "Saving notification settings...";

            var settings = new
            {
                Email = new
                {
                    Enabled = EnableEmailNotifications,
                    SmtpServer = SmtpServer,
                    SmtpPort = SmtpPort,
                    UseSsl = SmtpUseSsl,
                    Username = SmtpUsername,
                    Password = SmtpPassword,
                    From = EmailFrom,
                    To = EmailTo
                },
                Slack = new
                {
                    Enabled = EnableSlackNotifications,
                    WebhookUrl = SlackWebhookUrl,
                    Channel = SlackChannel,
                    Username = SlackUsername
                },
                Teams = new
                {
                    Enabled = EnableTeamsNotifications,
                    WebhookUrl = TeamsWebhookUrl
                },
                Webhook = new
                {
                    Enabled = EnableWebhookNotifications,
                    Url = WebhookUrl,
                    Method = WebhookMethod,
                    AuthHeader = WebhookAuthHeader
                }
            };

            await _apiClient.PostAsync<object, object>("notifications/settings", settings);

            StatusMessage = "Notification settings saved successfully";
            _dialogService.ShowSuccessMessage("Success", "Notification settings saved successfully.");
            _logger.LogInformation("Notification settings saved successfully");
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to save notification settings");
            StatusMessage = "Failed to save notification settings";
            _dialogService.ShowErrorMessage("Save Failed", ex.Message);
        }
        finally
        {
            IsBusy = false;
        }
    }

    private void LoadSettings()
    {
        // In a real implementation, load from configuration file or API
        _logger.LogInformation("Settings loaded");
    }

    private void ApplyTheme(string theme)
    {
        try
        {
            // In a real implementation, apply theme to application
            _logger.LogInformation("Theme changed to: {Theme}", theme);
        }
        catch (Exception ex)
        {
            _logger.LogError(ex, "Failed to apply theme");
        }
    }
}
