#Requires -Version 5.1

<#
.SYNOPSIS
    Developer environment module for DeployForge.

.DESCRIPTION
    Comprehensive developer environment configuration for Windows deployment images.
#>

enum DFDevProfile {
    WebFrontend   # HTML, CSS, JavaScript, TypeScript, React, Vue
    WebBackend    # Node.js, Python, Java, databases
    FullStack     # Complete web development stack
    Mobile        # Android, iOS, React Native, Flutter
    DataScience   # Python, R, Jupyter, ML frameworks
    DevOps        # Docker, Kubernetes, Terraform, CI/CD
    GameDev       # Unity, Unreal, C++, game development tools
    Embedded      # C, C++, Arduino, embedded systems
    Desktop       # .NET, Electron, Qt
    Minimal       # Just essentials
}

$script:LanguagePackages = @{
    python = "Python.Python.3.12"
    python311 = "Python.Python.3.11"
    nodejs = "OpenJS.NodeJS.LTS"
    java17 = "EclipseAdoptium.Temurin.17.JDK"
    java21 = "EclipseAdoptium.Temurin.21.JDK"
    dotnet = "Microsoft.DotNet.SDK.8"
    go = "GoLang.Go"
    rust = "Rustlang.Rustup"
    ruby = "RubyInstallerTeam.Ruby.3.2"
}

$script:DevToolPackages = @{
    git = "Git.Git"
    github_desktop = "GitHub.GitHubDesktop"
    postman = "Postman.Postman"
    docker_desktop = "Docker.DockerDesktop"
    windows_terminal = "Microsoft.WindowsTerminal"
    powershell7 = "Microsoft.PowerShell"
    vscode = "Microsoft.VisualStudioCode"
    vscode_insiders = "Microsoft.VisualStudioCode.Insiders"
}

$script:CloudToolPackages = @{
    azure_cli = "Microsoft.AzureCLI"
    aws_cli = "Amazon.AWSCLI"
    gcloud = "Google.CloudSDK"
    kubectl = "Kubernetes.kubectl"
    terraform = "Hashicorp.Terraform"
    helm = "Helm.Helm"
}

function Install-DFDevEnvironment {
    <#
    .SYNOPSIS
        Installs a complete developer environment.

    .PARAMETER MountPoint
        Path to the mounted image.

    .PARAMETER Profile
        Development profile to install.

    .EXAMPLE
        Install-DFDevEnvironment -MountPoint "C:\Mount" -Profile FullStack
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$MountPoint,

        [DFDevProfile]$Profile = [DFDevProfile]::Minimal
    )

    Write-DFLog -Message "Installing developer environment: $($Profile.ToString())" -Level Info

    # Enable developer mode
    Enable-DFDeveloperMode -MountPoint $MountPoint

    # Get profile configuration
    $profileConfig = Get-DFDevProfileConfig -Profile $Profile

    # Create installation scripts
    $scriptsDir = Join-Path $MountPoint "Windows\Setup\Scripts"
    if (-not (Test-Path $scriptsDir)) {
        New-Item -ItemType Directory -Path $scriptsDir -Force | Out-Null
    }

    # Generate installation script
    $scriptContent = @"
# Developer Environment Installation Script
# Generated by DeployForge - Profile: $($Profile.ToString())

Write-Host "Installing developer environment..." -ForegroundColor Cyan

# Check for winget
`$winget = Get-Command winget -ErrorAction SilentlyContinue
if (-not `$winget) {
    Write-Host "winget not available. Please install Windows Package Manager first." -ForegroundColor Red
    exit 1
}

# Languages
"@

    foreach ($lang in $profileConfig.Languages) {
        if ($script:LanguagePackages.ContainsKey($lang)) {
            $packageId = $script:LanguagePackages[$lang]
            $scriptContent += @"

Write-Host "Installing $lang..."
winget install --id $packageId --silent --accept-package-agreements --accept-source-agreements

"@
        }
    }

    $scriptContent += "`n# Development Tools`n"
    
    foreach ($tool in $profileConfig.Tools) {
        if ($script:DevToolPackages.ContainsKey($tool)) {
            $packageId = $script:DevToolPackages[$tool]
            $scriptContent += @"

Write-Host "Installing $tool..."
winget install --id $packageId --silent --accept-package-agreements --accept-source-agreements

"@
        }
    }

    if ($profileConfig.CloudTools.Count -gt 0) {
        $scriptContent += "`n# Cloud Tools`n"
        
        foreach ($tool in $profileConfig.CloudTools) {
            if ($script:CloudToolPackages.ContainsKey($tool)) {
                $packageId = $script:CloudToolPackages[$tool]
                $scriptContent += @"

Write-Host "Installing $tool..."
winget install --id $packageId --silent --accept-package-agreements --accept-source-agreements

"@
            }
        }
    }

    $scriptContent += @"

Write-Host "Developer environment installation complete!" -ForegroundColor Green
"@

    $scriptPath = Join-Path $scriptsDir "Install-DevEnvironment.ps1"
    Set-Content -Path $scriptPath -Value $scriptContent -Encoding UTF8

    # Enable WSL2 if required
    if ($profileConfig.EnableWSL2) {
        Enable-DFWSL2 -MountPoint $MountPoint
    }

    Write-DFLog -Message "Developer environment configured" -Level Info
}

function Get-DFDevProfileConfig {
    param([DFDevProfile]$Profile)

    $config = @{
        Languages = @()
        Tools = @('git', 'vscode', 'windows_terminal', 'powershell7')
        CloudTools = @()
        EnableWSL2 = $false
    }

    switch ($Profile) {
        'WebFrontend' {
            $config.Languages = @('nodejs')
            $config.EnableWSL2 = $true
        }
        'WebBackend' {
            $config.Languages = @('python', 'nodejs')
            $config.Tools += @('docker_desktop', 'postman')
            $config.EnableWSL2 = $true
        }
        'FullStack' {
            $config.Languages = @('python', 'nodejs', 'dotnet')
            $config.Tools += @('docker_desktop', 'postman', 'github_desktop')
            $config.CloudTools = @('kubectl', 'azure_cli')
            $config.EnableWSL2 = $true
        }
        'DataScience' {
            $config.Languages = @('python', 'nodejs')
            $config.EnableWSL2 = $true
        }
        'DevOps' {
            $config.Languages = @('python', 'go')
            $config.Tools += @('docker_desktop')
            $config.CloudTools = @('kubectl', 'terraform', 'helm', 'azure_cli', 'aws_cli')
            $config.EnableWSL2 = $true
        }
        'GameDev' {
            $config.Languages = @('dotnet')
            $config.Tools += @('github_desktop')
        }
        'Minimal' {
            $config.Languages = @('python')
        }
    }

    return $config
}

function Enable-DFDeveloperMode {
    <#
    .SYNOPSIS
        Enables Windows Developer Mode.

    .PARAMETER MountPoint
        Path to the mounted image.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$MountPoint
    )

    Write-DFLog -Message "Enabling Developer Mode" -Level Verbose

    $hivePath = Join-Path $MountPoint "Windows\System32\config\SOFTWARE"
    $hiveKey = "HKLM\TEMP_DF_SOFTWARE"

    try {
        & reg.exe load $hiveKey $hivePath 2>&1 | Out-Null
        & reg.exe add "$hiveKey\Microsoft\Windows\CurrentVersion\AppModelUnlock" /v AllowDevelopmentWithoutDevLicense /t REG_DWORD /d 1 /f | Out-Null
        & reg.exe add "$hiveKey\Microsoft\Windows\CurrentVersion\AppModelUnlock" /v AllowAllTrustedApps /t REG_DWORD /d 1 /f | Out-Null
        Write-DFLog -Message "Developer Mode enabled" -Level Info
    }
    finally {
        [gc]::Collect()
        Start-Sleep -Milliseconds 500
        & reg.exe unload $hiveKey 2>&1 | Out-Null
    }
}

function Enable-DFWSL2 {
    <#
    .SYNOPSIS
        Enables WSL2 feature.

    .PARAMETER MountPoint
        Path to the mounted image.
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$MountPoint
    )

    Write-DFLog -Message "Enabling WSL2 features" -Level Info

    try {
        & dism.exe /Image:"$MountPoint" /Enable-Feature /FeatureName:Microsoft-Windows-Subsystem-Linux /All /NoRestart 2>&1 | Out-Null
        & dism.exe /Image:"$MountPoint" /Enable-Feature /FeatureName:VirtualMachinePlatform /All /NoRestart 2>&1 | Out-Null
        Write-DFLog -Message "WSL2 features enabled" -Level Info
    }
    catch {
        Write-DFLog -Message "Failed to enable WSL2: $_" -Level Warning
    }
}

function Set-DFGitConfig {
    <#
    .SYNOPSIS
        Configures Git for the image.

    .PARAMETER MountPoint
        Path to the mounted image.

    .PARAMETER Name
        Git user name.

    .PARAMETER Email
        Git user email.

    .PARAMETER Editor
        Default editor (default: code).
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true)]
        [string]$MountPoint,

        [Parameter(Mandatory = $true)]
        [string]$Name,

        [Parameter(Mandatory = $true)]
        [string]$Email,

        [string]$Editor = "code"
    )

    $scriptsDir = Join-Path $MountPoint "Windows\Setup\Scripts"
    if (-not (Test-Path $scriptsDir)) {
        New-Item -ItemType Directory -Path $scriptsDir -Force | Out-Null
    }

    $scriptContent = @"
# Git Configuration Script
git config --global user.name "$Name"
git config --global user.email "$Email"
git config --global core.editor "$Editor --wait"
git config --global init.defaultBranch main
git config --global pull.rebase false
git config --global credential.helper wincred
Write-Host "Git configured for $Name <$Email>"
"@

    $scriptPath = Join-Path $scriptsDir "Configure-Git.ps1"
    Set-Content -Path $scriptPath -Value $scriptContent -Encoding UTF8

    Write-DFLog -Message "Git configuration script created" -Level Info
}

Write-Verbose "Loaded DeployForge DevEnvironment module"
