"""
DeployForge v0.3.0 Example: Automated Enterprise Deployment

This example demonstrates creating a complete automated enterprise deployment
solution including:
- UEFI bootable disk with proper partitioning
- Automated domain join via unattend.xml
- Multi-language support (European languages)

Requirements:
- DeployForge 0.3.0 or later
- Windows ADK (for WinPE ISO creation on Windows)
- Language pack .cab files

Usage:
    python enterprise_deployment.py
"""

from pathlib import Path
from deployforge.partitions import create_uefi_bootable_image, PartitionManager
from deployforge.unattend import (
    create_enterprise_unattend,
    UnattendGenerator,
    UnattendConfig,
    NetworkSettings,
    OOBESettings
)
from deployforge.languages import (
    LanguageManager,
    create_european_multilingual,
    LanguageSettings
)


def main():
    """Create a complete enterprise deployment configuration"""

    print("=" * 70)
    print("DeployForge v0.3.0 - Enterprise Deployment Example")
    print("=" * 70)
    print()

    # Configuration
    disk_image_path = Path("enterprise_deployment.vhdx")
    unattend_path = Path("autounattend.xml")
    disk_size_gb = 100

    # Domain configuration
    domain = "corporate.local"
    domain_admin = "Administrator"
    domain_password = "SecurePassword123!"  # Use secure password in production
    product_key = "XXXXX-XXXXX-XXXXX-XXXXX-XXXXX"  # Replace with real key

    print("Configuration:")
    print(f"  Disk Image: {disk_image_path}")
    print(f"  Disk Size: {disk_size_gb} GB")
    print(f"  Domain: {domain}")
    print(f"  Unattend File: {unattend_path}")
    print()

    # Step 1: Create UEFI bootable disk with partitions
    print("[1/4] Creating UEFI bootable disk image...")
    print(f"      This will create a {disk_size_gb}GB disk with:")
    print("      - 100MB EFI System Partition (FAT32)")
    print("      - 16MB Microsoft Reserved Partition")
    print("      - ~98GB Windows Partition (NTFS)")
    print("      - 500MB Recovery Partition (NTFS)")
    print()

    pm = create_uefi_bootable_image(
        disk_image_path,
        disk_size_gb=disk_size_gb,
        include_recovery=True
    )

    # Display partition layout
    print("      Created partition layout:")
    for part in pm.layout.partitions:
        print(f"        {part.number}. {part.name:30} {part.size_gb:6.2f} GB  {part.filesystem or 'N/A':8}")
    print()

    # Export partition layout for reference
    layout_json = Path("partition_layout.json")
    pm.export_layout(layout_json)
    print(f"      ✓ Partition layout exported to {layout_json}")
    print()

    # Step 2: Generate enterprise unattend.xml
    print("[2/4] Generating enterprise unattend.xml...")
    print("      Features:")
    print("      - Automated domain join")
    print("      - Skip OOBE screens")
    print("      - Time zone configuration")
    print("      - Product key activation")
    print()

    # Create advanced configuration
    config = UnattendConfig(
        product_key=product_key,
        organization="Acme Corporation"
    )

    # Network settings for domain join
    config.network_settings = NetworkSettings(
        computer_name=None,  # Auto-generated by Windows
        domain=domain,
        domain_username=domain_admin,
        domain_password=domain_password
    )

    # OOBE settings - skip everything for enterprise
    config.oobe_settings = OOBESettings(
        hide_eula_page=True,
        hide_oem_registration_page=True,
        hide_online_account_screens=True,
        hide_wireless_setup=True,
        protect_your_pc=1,  # Recommended settings
        skip_machine_oobe=True
    )

    # Add first logon commands
    config.add_first_logon_command(
        'powershell.exe -ExecutionPolicy Bypass -File C:\\Deploy\\Configure-Workstation.ps1'
    )
    config.add_first_logon_command(
        'reg import C:\\Deploy\\GroupPolicy.reg'
    )

    # Generate and save
    generator = UnattendGenerator(config)
    generator.save(unattend_path)

    print(f"      ✓ Generated {unattend_path}")
    print(f"      ✓ Domain: {domain}")
    print(f"      ✓ OOBE screens: Hidden")
    print(f"      ✓ First logon commands: 2")
    print()

    # Step 3: Configure multi-language support
    print("[3/4] Configuring multi-language support...")
    print("      Languages: English (UK), German, French, Spanish, Italian")
    print()

    # Create European multilingual configuration
    lang_config = create_european_multilingual()

    print(f"      Default Language: {lang_config.default_language}")
    print(f"      Fallback Language: {lang_config.fallback_language}")
    print(f"      Installed Languages: {', '.join(lang_config.installed_languages)}")
    print(f"      Keyboard Layouts: {len(lang_config.keyboard_layouts)}")
    print(f"      Time Zone: {lang_config.time_zone}")
    print()

    # Export language configuration
    lang_config_json = Path("language_config.json")
    import json
    with open(lang_config_json, 'w', encoding='utf-8') as f:
        json.dump(lang_config.to_dict(), f, indent=2, ensure_ascii=False)

    print(f"      ✓ Language configuration exported to {lang_config_json}")
    print()

    # Note about language pack installation
    print("      NOTE: To apply language packs to install.wim:")
    print("      1. Mount the Windows image:")
    print("         dism /Mount-Wim /WimFile:install.wim /Index:1 /MountDir:C:\\mount")
    print("      2. Add each language pack:")
    print("         dism /Image:C:\\mount /Add-Package /PackagePath:de-DE-LanguagePack.cab")
    print("      3. Set default language:")
    print("         dism /Image:C:\\mount /Set-AllIntl:de-DE")
    print("      4. Unmount and save:")
    print("         dism /Unmount-Wim /MountDir:C:\\mount /Commit")
    print()

    # Step 4: Summary and next steps
    print("[4/4] Deployment package summary")
    print("=" * 70)
    print()
    print("Created Files:")
    print(f"  ✓ {disk_image_path} - UEFI bootable disk ({disk_size_gb} GB)")
    print(f"  ✓ {unattend_path} - Automated installation answer file")
    print(f"  ✓ {layout_json} - Partition layout reference")
    print(f"  ✓ {lang_config_json} - Language configuration")
    print()
    print("Next Steps:")
    print("  1. Copy Windows installation files to the Windows partition")
    print("  2. Place autounattend.xml in the root of the installation media")
    print("  3. Apply language packs to install.wim (see commands above)")
    print("  4. Create deployment scripts in C:\\Deploy folder")
    print("  5. Test deployment in VM environment")
    print("  6. Deploy to production workstations")
    print()
    print("Deployment Features:")
    print("  • Automated domain join to", domain)
    print("  • UEFI boot with GPT partitioning")
    print("  • Recovery partition for Windows RE")
    print("  • Multi-language support (5 European languages)")
    print("  • Unattended installation (zero-touch)")
    print("  • Custom first logon configuration")
    print()
    print("=" * 70)
    print("Enterprise deployment package created successfully!")
    print("=" * 70)


if __name__ == "__main__":
    main()
